### ISSUE TITLE
Scaffold molecule cloud

### ISSUE THREAD

**Issue by diallobakary4** [kotori-y/Scopy#1]
I want run Mocule cloud following instructions [here](https://github.com/kotori-y/Scopy/tree/7c868f351f5756e181d7d91bc4d58adbc4af535c/scopy/data/MC/mcloud).
Point 1: "1 - modify the source of MCloud.java (around line 570), comment the call to the constructor of TestMolHandler and uncomment the one for AvalonMolHandler 
" 
There is no line 570 not AvalonMolHandler or TestMolHandler related constructors.

**Comment by kotori-y** [comment]
Thanks for your issue!

The mcloud script was obtained from this [article](http://www.jcheminf.com/content/4/1/12/) and be revised by us. However, regrettably, we didn't  change the *readme.txt* in time. We are sorry for the inconvenience caused to you.

If you want to use the mcloud, there are two method

1. Run with the command line: 

   change your disk to mcloud folder

   ```
   cd scopy/data/MC/mcloud
   ```

   run following command line

   ```
   java -cp ".;depictjni.jar;depict.jar" ertl/mcloud/MCloud -f .\scaffolds.smi
   ```

2. Run with <code>Scopy</code> package

   ```python
   from scopy.ScoVisualize.mcloud import ShowMcloud
   
   ShowMcloud(file = "path_to_data/scaffolds.smi")
   ```

   **notice:** the <code>file</code> should be an absolute path.

Hope it works for you, have a nice day!
